### ISSUE TITLE
不能添加第二作者

### ISSUE THREAD

**Issue by MingFengX** [EthanDeng/Chinese-ERJ#1]
我希望在文章中添加第二作者，结果无法顺利编译，故障代码如下：
```
\documentclass{chinese-erj}
\title{南京爱情故事}
\author{乔英子\and方一凡%
\thanks{Email: {yingzi2000@nyu.edu.cn}}
\thanks{Email: {yifan@pku.edu.cn}}}

\begin{document}
\maketitle
\end{document}

```

**Comment by hushidong** [comment]
把\and换成空格试试。

cls目前没有考虑用\and 分隔的作者列表，而是原样输出的。

**Comment by MingFengX** [comment]
如果换成空格两个名字就没办法隔开。
如果用\quad或\qquad的话，无法使用XeLaTex编译。
如果使用PDFLaTeX编译的话，第二次pdfLaTeX编译时，无法识别引文信息。

此处叨扰了。

**Comment by hushidong** [comment]
那就用~符号，或者hspace

**Comment by EthanDeng** [comment]
见更新 [53edb85](https://github.com/EthanDeng/Chinese-ERJ/commit/53edb8577410c3271e661739610164941ef6770b)。
